version: '3.0'

services:
  mc:
    image: itzg/minecraft-server:java21-graalvm
    ports:
      - 25565:25565
    environment:
      EULA: 'true'
      MOD_PLATFORM: MODRINTH
#      MODRINTH_MODPACK: https://modrinth.com/modpack/create-extra/version/z2oEWZQ5
      MODRINTH_MODPACK: /create_sin_fancy_1.0.0.mrpack
#      MODRINTH_EXCLUDE_FILES: fancymenu,beansBackpack,backpack
      MEMORY: 2G
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - mc-data:/data
  init-filebrowser:
    image: filebrowser/filebrowser
    entrypoint: sh -c
    command:
      - "chown -R 1000: /database"
    restart: 'no'
    volumes:
      - filebrowser-db:/database
  filebrowser:
    image: filebrowser/filebrowser
    depends_on:
      init-filebrowser:
        condition: service_completed_successfully
    user: "1000:1000"
    environment:
      FB_DATABASE: /database/filebrowser.db
    volumes:
      - mc-data:/srv
      - filebrowser-db:/database
    ports:
      - "25580:80"
  ngrok:
    image: ngrok/ngrok:alpine
    restart: unless-stopped
    environment:
      NGROK_AUTHTOKEN: ${AUTH_TOKEN}
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./.ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040

volumes:
  mc-data: {}
  filebrowser-db: {}