version: '3.8'

services:
  mc:
    image: itzg/minecraft-server:java21-graalvm
    ports:
      - 25565:25565
    environment:
      EULA: 'true'
      MOD_PLATFORM: MODRINTH
      MODRINTH_MODPACK: /mrpack/server.mrpack
      MEMORY: 2G
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - minecraft_data:/data
      - ./mrpack:/mrpack
  init-filebrowser:
    image: filebrowser/filebrowser
    entrypoint: sh -c
    command:
      - "chown -R 1000: /database"
    restart: 'no'
    volumes:
      - filebrowser-db:/database
  filebrowser:
    image: filebrowser/filebrowser
    depends_on:
      init-filebrowser:
        condition: service_completed_successfully
    user: "1000:1000"
    environment:
      FB_DATABASE: /database/filebrowser.db
    volumes:
      - minecraft_data:/srv
      - filebrowser-db:/database
    ports:
      - "25580:80"
  ngrok:
    image: ngrok/ngrok:alpine
    restart: unless-stopped
    environment:
      NGROK_AUTHTOKEN: ${AUTH_TOKEN}
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./.ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
#  backup:
#    build: ./backup
#    volumes:
#      - minecraft_data:/data
#      - ./backup:/backup

volumes:
  minecraft_data: {}
  filebrowser-db: {}
